/* eslint-disable @next/next/no-page-custom-font */

import type { Metadata } from "next";
import Image from "next/image";
import '../styles/globals.scss';
import ReactQueryProvider from "./Providers";
import bottomBackground from "./bottomBackground.svg";
import bottomBackgroundMobile from "./bottomBackgroundMobile.svg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <div className="bottom-background-wrapper">
          <Image
            src={bottomBackground}
            className="bottom-background-img"
            alt="bottom background"
            priority
          />
        </div>
        <div className="bottom-background-wrapper-mobile">
          <Image
            src={bottomBackgroundMobile}
            className="bottom-background-img"
            alt="bottom background"
            priority
          />
        </div>
      </body>
    </html>
  );
}